name: CD

#CD 워크플로우 실행 트리거 설정
on:
 push:
   branches: [ main ]

env:
  S3_BUCKET_NAME: feedb-bucket
  PROJECT_NAME: cicdtest
  
 
jobs:
  build:
    name: CD
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'zulu'
          
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash
      # .env 파일 생성
      - name: Create .env file
        run: |
          touch .env
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
          echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> .env
          echo "JWT_SECRET=VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHb17" >> .env
          cat .env

      - name: Build with Gradle
        run: ./gradlew build
        shell: bash

      - name: Make zip file
        run: zip -r ./$GITHUB_SHA.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}    

    # script file 복사(지금은 ./deploy폴더에 복사하는 이유를 뚜렷이 모르겠다. 추후에 생 해도 문제 없으면 주석)
     # - name: Copy script
     #   run : cp ./scripts/*.sh ./deploy
        
    #S3에 업로드
      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$S3_BUCKET_NAME/$PROJECT_NAME/$GITHUB_SHA.zip

    # Deploy
      - name: Deploy
        run: |
          aws deploy create-deployment \
          --application-name FeedB-CICD \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --deployment-group-name cicd-FeedB \
          --file-exists-behavior OVERWRITE \
          --s3-location bucket=feedb-bucket,bundleType=zip,key=cicdtest/$GITHUB_SHA.zip \
